name: Start or Stop Ec2 Instance
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (start or stop)'
        required: true
        default: 'start'
        type: choice
        options:
          - start
          - stop
jobs:
  ec2-instance-action:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: "${{ github.event.inputs.action }} EC2 Instance"
        id: ec2_action
        run: |
          if [ "${{ github.event.inputs.action }}" = "start" ]; then
            echo "Starting EC2 instance..."
            aws ec2 start-instances --instance-ids ${{ secrets.AWS_INSTANCE_ID }}
            aws ec2 wait instance-running --instance-ids ${{ secrets.AWS_INSTANCE_ID }}
            echo "EC2 instance started successfully."

            PUBLIC_IP=$(aws ec2 describe-instances \
              --instance-ids ${{ secrets.AWS_INSTANCE_ID }} \
              --query "Reservations[0].Instances[0].PublicIpAddress" \
              --output text)

            echo "Public IP is: $PUBLIC_IP"
          else
            echo "Stopping EC2 instance..."
            aws ec2 stop-instances --instance-ids ${{ secrets.AWS_INSTANCE_ID }}
          fi